/**
 * Created by vladtomsa on 22/11/2018
 */
export const administrationsConstants =  {
  ON_GET_ADMIN_PROVIDERS_INIT: '@ON_GET_ADMIN_PROVIDERS_INIT',
  ON_GET_ADMIN_PROVIDERS_SUCCESS: '@ON_GET_ADMIN_PROVIDERS_SUCCESS',
  ON_GET_ADMIN_PROVIDERS_FAILURE: '@ON_GET_ADMIN_PROVIDERS_FAILURE',
  ON_SAVE_ADMIN_PROVIDERS_INIT: '@ON_SAVE_ADMIN_PROVIDERS_INIT',
  ON_SAVE_ADMIN_PROVIDERS_SUCCESS: '@ON_SAVE_ADMIN_PROVIDERS_SUCCESS',
  ON_SAVE_ADMIN_PROVIDERS_FAILURE: '@ON_SAVE_ADMIN_PROVIDERS_FAILURE',
  ON_RESET_ADMIN_PROVIDERS: '@ON_RESET_ADMIN_PROVIDERS',
  ON_SELECT_PROVIDER: '@ON_SELECT_PROVIDER_ADMIN',
  ON_DESELECT_PROVIDER: '@ON_DESELECT_PROVIDER_ADMIN',
};
