/**
 * Created by vladtomsa on 09/10/2018
 */
export const attributesConstants =  {
  ON_GET_ATTRIBUTE_TYPES_INIT: '@ON_GET_ATTRIBUTE_TYPES_INIT',
  ON_GET_ATTRIBUTE_TYPES_SUCCESS: '@ON_GET_ATTRIBUTE_TYPES_SUCCESS',
  ON_GET_ATTRIBUTE_TYPES_FAILURE: '@ON_GET_ATTRIBUTE_TYPES_FAILURE',
  ON_GET_USER_ATTRIBUTES_INIT: '@ON_GET_USER_ATTRIBUTES_INIT',
  ON_GET_USER_ATTRIBUTES_SUCCESS: '@ON_GET_USER_ATTRIBUTES_SUCCESS',
  ON_GET_USER_ATTRIBUTES_FAILURE: '@ON_GET_USER_ATTRIBUTES_FAILURE',
  ON_GET_USER_SENT_VALIDATION_REQUESTS_INIT: '@ON_GET_USER_SENT_VALIDATION_REQUESTS_INIT',
  ON_GET_USER_SENT_VALIDATION_REQUESTS_SUCCESS: '@ON_GET_USER_SENT_VALIDATION_REQUESTS_SUCCESS',
  ON_GET_USER_SENT_VALIDATION_REQUESTS_FAILURE: '@ON_GET_USER_SENT_VALIDATION_REQUESTS_FAILURE',
  ON_GET_VALIDATION_REQUESTS_INIT: '@ON_GET_VALIDATION_REQUESTS_INIT',
  ON_GET_VALIDATION_REQUESTS_SUCCESS: '@ON_GET_VALIDATION_REQUESTS_SUCCESS',
  ON_GET_VALIDATION_REQUESTS_FAILURE: '@ON_GET_VALIDATION_REQUESTS_FAILURE',
  ON_CREATE_USER_ATTRIBUTES_INIT: '@ON_CREATE_USER_ATTRIBUTES_INIT',
  ON_CREATE_USER_ATTRIBUTES_SUCCESS: '@ON_CREATE_USER_ATTRIBUTES_SUCCESS',
  ON_CREATE_USER_ATTRIBUTES_FAILURE: '@ON_CREATE_USER_ATTRIBUTES_FAILURE',
  ON_CREATE_VALIDATION_REQUEST_INIT: '@ON_CREATE_VALIDATION_REQUEST_INIT',
  ON_CREATE_VALIDATION_REQUEST_SUCCESS: '@ON_CREATE_VALIDATION_REQUEST_SUCCESS',
  ON_CREATE_VALIDATION_REQUEST_FAILURE: '@ON_CREATE_VALIDATION_REQUEST_FAILURE',
  ON_GET_FILE_ATTRIBUTE_INIT: '@ON_GET_FILE_ATTRIBUTE_INIT',
  ON_GET_FILE_ATTRIBUTE_SUCCESS: '@ON_GET_FILE_ATTRIBUTE_SUCCESS',
  ON_GET_FILE_ATTRIBUTE_FAILURE: '@ON_GET_FILE_ATTRIBUTE_FAILURE',
  ON_DESELECT_FILE_ATTRIBUTE: '@ON_DESELECT_FILE_ATTRIBUTE',
  ON_VALIDATION_UPDATE_INIT: '@ON_VALIDATION_UPDATE_INIT',
  ON_VALIDATION_UPDATE_DONE: '@ON_VALIDATION_UPDATE_DONE',
};
