/**
 * Created by vladtomsa on 01/10/2018
 */
export const authConstants =  {
  ON_CONFIRM_ACCOUNT_INIT: '@ON_CONFIRM_ACCOUNT_INIT',
  ON_CONFIRM_ACCOUNT_SUCCESS: '@ON_CONFIRM_ACCOUNT_SUCCESS',
  ON_CONFIRM_ACCOUNT_FAILURE: '@ON_CONFIRM_ACCOUNT_FAILURE',
  ON_CREATE_ACCOUNT_INIT: '@ON_CREATE_ACCOUNT_INIT',
  ON_CREATE_ACCOUNT_SUCCESS: '@ON_CREATE_ACCOUNT_SUCCESS',
  ON_CREATE_ACCOUNT_FAILURE: '@ON_CREATE_ACCOUNT_FAILURE',
  ON_UPDATE_ACCOUNT_INIT: '@ON_UPDATE_ACCOUNT_INIT',
  ON_UPDATE_ACCOUNT_FAILURE: '@ON_UPDATE_ACCOUNT_FAILURE',
  ON_LOGIN_INIT: '@ON_LOGIN_INIT',
  ON_LOGIN_SUCCESS: '@ON_LOGIN_SUCCESS',
  ON_LOGIN_FAILURE: '@ON_LOGIN_FAILURE',
  ON_LOGOUT: '@ON_LOGOUT',
};

export const USER_INFO_STORAGE_KEY = 'PRSN_USER_INFO_STORAGE_KEY';
export const REMEMBER_ME_STORAGE_KEY = 'PRSN_REMEMBER_ME_STORAGE_KEY';
export const USER_LOGIN_TOKEN_STORAGE_KEY = 'PRSN_USER_LOGIN_TOKEN_STORAGE_KEY';
