/**
 * Created by vladtomsa on 09/10/2018
 */
export const blockchainAccountConstants =  {
  ON_GET_BLOCKCHAIN_ACCOUNT_INIT: '@ON_GET_BLOCKCHAIN_ACCOUNT_INIT',
  ON_GET_BLOCKCHAIN_ACCOUNT_SUCCESS: '@ON_GET_BLOCKCHAIN_ACCOUNT_SUCCESS',
  ON_GET_BLOCKCHAIN_ACCOUNT_FAILURE: '@ON_GET_BLOCKCHAIN_ACCOUNT_FAILURE',
};
