/**
 * Created by vladtomsa on 10/10/2018
 */
export const globalConstants = {
  ON_GET_COUNTRIES_SUCCESS: '@ON_GET_COUNTRIES_SUCCESS',
  ON_GET_COUNTRIES_ERROR: '@ON_GET_COUNTRIES_ERROR',
  ON_STORE_PASSPHRASE: '@ON_STORE_PASSPHRASE',
  ON_REMOVE_PASSPHRASE: '@ON_REMOVE_PASSPHRASE',
  OPEN_SIDENAV: '@ON_OPEN_SIDENAV',
  CLOSE_SIDENAV: '@ON_CLOSE_SIDENAV',
};
