/**
 * Created by vladtomsa on 03/12/2018
 */
export const identityUseConstants = {
  GET_IDENTITY_USE_REQUEST_INIT: '@GET_IDENTITY_USE_REQUEST_INIT',
  GET_IDENTITY_USE_REQUEST_SUCCESS: '@GET_IDENTITY_USE_REQUEST_SUCCESS',
  GET_IDENTITY_USE_REQUEST_FAILURE: '@GET_IDENTITY_USE_REQUEST_FAILURE',

  ON_SELECT_SERVICE_FOR_IDENTITY_USE: '@ON_SELECT_SERVICE_FOR_IDENTITY_USE',
  ON_DESELECT_SERVICE_FOR_IDENTITY_USE: '@ON_DESELECT_SERVICE_FOR_IDENTITY_USE',

  CREATE_IDENTITY_USE_REQUEST_INIT: '@CREATE_IDENTITY_USE_REQUEST_INIT',
  CREATE_IDENTITY_USE_REQUEST_SUCCESS: '@CREATE_IDENTITY_USE_REQUEST_SUCCESS',
  CREATE_IDENTITY_USE_REQUEST_FAILURE: '@CREATE_IDENTITY_USE_REQUEST_FAILURE',

  ON_IDENTITY_USE_UPDATE_INIT: '@ON_IDENTITY_USE_UPDATE_INIT',
  ON_IDENTITY_USE_UPDATE_DONE: '@ON_IDENTITY_USE_UPDATE_DONE',
  RESET_IDENTITY_REQUESTS: '@ON_RESET_IDENTITY_REQUESTS',
};
