/**
 * Created by vladtomsa on 08/11/2018
 */
export const notariesConstants =  {
  ON_GET_NOTARIES_INIT: '@ON_GET_NOTARIES_INIT',
  ON_GET_NOTARIES_SUCCESS: '@ON_GET_NOTARIES_SUCCESS',
  ON_GET_NOTARIES_FAILURE: '@ON_GET_NOTARIES_FAILURE',
  ON_RESET_NOTARIES: '@ON_RESET_NOTARIES',
};
