/**
 * Created by vladtomsa on 29/11/2018
 */
export const providersConstants = {
  ON_GET_PROVIDERS_INIT: '@ON_GET_PROVIDERS_INIT',
  ON_GET_PROVIDERS_SUCCESS: '@ON_GET_PROVIDERS_SUCCESS',
  ON_GET_PROVIDERS_FAILURE: '@ON_GET_PROVIDERS_FAILURE',
  ON_GET_PROVIDER_BY_ADDRESS_INIT: '@ON_GET_PROVIDER_BY_ADDRESS_INIT',
  ON_GET_PROVIDER_BY_ADDRESS_SUCCESS: '@ON_GET_PROVIDER_BY_ADDRESS_SUCCESS',
  ON_GET_PROVIDER_BY_ADDRESS_FAILURE: '@ON_GET_PROVIDER_BY_ADDRESS_FAILURE',
};
