/**
 * Created by vladtomsa on 28/11/2018
 */
export const providerConstants =  {
  ON_GET_PROVIDER_SERVICES_INIT: '@ON_GET_PROVIDER_SERVICES_INIT',
  ON_GET_PROVIDER_SERVICES_SUCCESS: '@ON_GET_PROVIDER_SERVICES_SUCCESS',
  ON_GET_PROVIDER_SERVICES_FAILURE: '@ON_GET_PROVIDER_SERVICES_FAILURE',

  ON_CREATE_PROVIDER_SERVICE_INIT: '@ON_CREATE_PROVIDER_SERVICE_INIT',
  ON_CREATE_PROVIDER_SERVICE_SUCCESS: '@ON_CREATE_PROVIDER_SERVICE_SUCCESS',
  ON_CREATE_PROVIDER_SERVICE_FAILURE: '@ON_CREATE_PROVIDER_SERVICE_FAILURE',

  ON_SELECT_PROVIDER_SERVICE_INFO: '@ON_SELECT_PROVIDER_SERVICE_INFO',
  ON_DESELECT_PROVIDER_SERVICE_INFO: '@ON_DESELECT_PROVIDER_SERVICE_INFO',

  ON_INACTIVATE_SERVICE_SELECT: '@ON_INACTIVATE_SERVICE_SELECT',
  ON_INACTIVATE_SERVICE_DESELECT: '@ON_INACTIVATE_SERVICE_DESELECT',
  ON_INACTIVATE_SERVICE: '@ON_INACTIVATE_SERVICE_INIT',
  ON_INACTIVATE_SERVICE_DONE: '@ON_INACTIVATE_SERVICE_DONE',

  ON_RESET_PROVIDER_SERVICES: '@ON_RESET_PROVIDER_SERVICES',
};
