/**
 * Created by vladtomsa on 28/11/2018
 */
export const servicesConstants =  {
  ON_GET_SERVICES_INIT: '@ON_GET_SERVICES_INIT',
  ON_GET_SERVICES_SUCCESS: '@ON_GET_SERVICES_SUCCESS',
  ON_GET_SERVICES_FAILURE: '@ON_GET_SERVICES_FAILURE',
  ON_RESET_SERVICES: '@ON_RESET_SERVICES',
};
