/**
 * Created by vladtomsa on 26/11/2018
 */
export const subscriptionConstants = {
  ON_GET_SUBSCRIPTIONS_INIT: '@ON_GET_SUBSCRIPTIONS_INIT',

  ON_GET_SUBSCRIPTIONS_SUCCESS: '@ON_GET_SUBSCRIPTIONS_SUCCESS',

  ON_GET_SUBSCRIPTIONS_FAILURE: '@ON_GET_SUBSCRIPTIONS_FAILURE',

  ON_CREATE_SUBSCRIPTIONS_INIT: '@ON_CREATE_SUBSCRIPTIONS_INIT',

  ON_CREATE_SUBSCRIPTIONS_SUCCESS: '@ON_CREATE_SUBSCRIPTIONS_SUCCESS',

  ON_CREATE_SUBSCRIPTIONS_FAILURE: '@ON_CREATE_SUBSCRIPTIONS_FAILURE',
};
